// src/components/BubbleToolbar.tsx
"use client";

import { BubbleMenu } from "@tiptap/react/menus";
import type { Editor } from "@tiptap/react";
import {
  Bold,
  Italic,
  Underline as UnderlineIcon,
  Strikethrough,
  Highlighter,
  LinkIcon,
  AlignLeft,
  AlignCenter,
  AlignRight,
  Heading1,
  Heading2,
  Heading3,
  Type,
} from "lucide-react";
import { useCallback, useState } from "react";
import { cn } from "../utils/cn";

function BubbleButton({
  onClick,
  active,
  title,
  children,
}: {
  onClick: () => void;
  active?: boolean;
  title: string;
  children: React.ReactNode;
}) {
  return (
    <button
      type="button"
      onClick={onClick}
      title={title}
      className={cn(
        "p-1.5 rounded-md transition-colors",
        active
          ? "bg-white/20 text-white"
          : "text-white/70 hover:text-white hover:bg-white/10"
      )}
    >
      {children}
    </button>
  );
}

function BubbleDivider() {
  return <div className="w-px h-5 bg-white/20 mx-0.5" />;
}

interface BubbleToolbarProps {
  editor: Editor;
}

export function BubbleToolbar({ editor }: BubbleToolbarProps) {
  const [showHeadings, setShowHeadings] = useState(false);
  const iconSize = 14;

  const addLink = useCallback(() => {
    const previousUrl = editor.getAttributes("link").href || "";
    const url = window.prompt("링크 URL을 입력하세요", previousUrl);
    if (url === null) return;
    if (url === "") {
      editor.chain().focus().extendMarkRange("link").unsetLink().run();
    } else {
      editor
        .chain()
        .focus()
        .extendMarkRange("link")
        .setLink({ href: url })
        .run();
    }
  }, [editor]);

  const getCurrentBlockLabel = () => {
    if (editor.isActive("heading", { level: 1 })) return "제목 1";
    if (editor.isActive("heading", { level: 2 })) return "제목 2";
    if (editor.isActive("heading", { level: 3 })) return "제목 3";
    return "본문";
  };

  return (
    <BubbleMenu
      editor={editor}
      options={{
        placement: "top",
      }}
      shouldShow={({ editor: e, state }) => {
        const { from, to } = state.selection;
        if (from === to) return false;
        if (e.isActive("codeBlock")) return false;
        if (e.isActive("image")) return false;
        return true;
      }}
    >
      <div className="flex items-center gap-0.5 px-1.5 py-1 bg-foreground rounded-lg shadow-xl">
        <div className="relative">
          <button
            type="button"
            onClick={() => setShowHeadings(!showHeadings)}
            className="flex items-center gap-1 px-2 py-1.5 rounded-md text-xs font-medium text-white/80 hover:text-white hover:bg-white/10 transition-colors"
          >
            <Type size={12} />
            {getCurrentBlockLabel()}
          </button>
          {showHeadings && (
            <div className="absolute bottom-full left-0 mb-1 bg-foreground rounded-lg shadow-xl border border-white/10 py-1 min-w-[120px]">
              <button
                type="button"
                className={cn(
                  "w-full flex items-center gap-2 px-3 py-1.5 text-xs transition-colors",
                  !editor.isActive("heading")
                    ? "text-white bg-white/10"
                    : "text-white/70 hover:text-white hover:bg-white/10"
                )}
                onClick={() => {
                  editor.chain().focus().setParagraph().run();
                  setShowHeadings(false);
                }}
              >
                <Type size={12} /> 본문
              </button>
              {[1, 2, 3].map((level) => {
                const Icon = level === 1 ? Heading1 : level === 2 ? Heading2 : Heading3;
                return (
                  <button
                    key={level}
                    type="button"
                    className={cn(
                      "w-full flex items-center gap-2 px-3 py-1.5 text-xs transition-colors",
                      editor.isActive("heading", { level })
                        ? "text-white bg-white/10"
                        : "text-white/70 hover:text-white hover:bg-white/10"
                    )}
                    onClick={() => {
                      editor
                        .chain()
                        .focus()
                        .toggleHeading({ level: level as 1 | 2 | 3 })
                        .run();
                      setShowHeadings(false);
                    }}
                  >
                    <Icon size={12} /> 제목 {level}
                  </button>
                );
              })}
            </div>
          )}
        </div>

        <BubbleDivider />

        <BubbleButton
          onClick={() => editor.chain().focus().toggleBold().run()}
          active={editor.isActive("bold")}
          title="굵게"
        >
          <Bold size={iconSize} />
        </BubbleButton>
        <BubbleButton
          onClick={() => editor.chain().focus().toggleItalic().run()}
          active={editor.isActive("italic")}
          title="기울임"
        >
          <Italic size={iconSize} />
        </BubbleButton>
        <BubbleButton
          onClick={() => editor.chain().focus().toggleUnderline().run()}
          active={editor.isActive("underline")}
          title="밑줄"
        >
          <UnderlineIcon size={iconSize} />
        </BubbleButton>
        <BubbleButton
          onClick={() => editor.chain().focus().toggleStrike().run()}
          active={editor.isActive("strike")}
          title="취소선"
        >
          <Strikethrough size={iconSize} />
        </BubbleButton>
        <BubbleButton
          onClick={() => editor.chain().focus().toggleHighlight().run()}
          active={editor.isActive("highlight")}
          title="하이라이트"
        >
          <Highlighter size={iconSize} />
        </BubbleButton>

        <BubbleDivider />

        <BubbleButton
          onClick={addLink}
          active={editor.isActive("link")}
          title="링크"
        >
          <LinkIcon size={iconSize} />
        </BubbleButton>

        <BubbleDivider />

        <BubbleButton
          onClick={() => editor.chain().focus().setTextAlign("left").run()}
          active={editor.isActive({ textAlign: "left" })}
          title="왼쪽 정렬"
        >
          <AlignLeft size={iconSize} />
        </BubbleButton>
        <BubbleButton
          onClick={() => editor.chain().focus().setTextAlign("center").run()}
          active={editor.isActive({ textAlign: "center" })}
          title="가운데 정렬"
        >
          <AlignCenter size={iconSize} />
        </BubbleButton>
        <BubbleButton
          onClick={() => editor.chain().focus().setTextAlign("right").run()}
          active={editor.isActive({ textAlign: "right" })}
          title="오른쪽 정렬"
        >
          <AlignRight size={iconSize} />
        </BubbleButton>
      </div>
    </BubbleMenu>
  );
}

// src/components/BubbleToolbar.svelte
<script lang="ts">
  import type { Editor } from "@tiptap/core";
  import { BubbleMenuPlugin } from "@tiptap/extension-bubble-menu";
  import { PluginKey } from "@tiptap/pm/state";
  import { onMount } from "svelte";

  const bubbleToolbarKey = new PluginKey("bubbleToolbar");
  import {
    Bold,
    Italic,
    Underline as UnderlineIcon,
    Strikethrough,
    Highlighter,
    LinkIcon,
    AlignLeft,
    AlignCenter,
    AlignRight,
    Heading1,
    Heading2,
    Heading3,
    Type,
    Code,
    Palette,
  } from "lucide-svelte";
  import { cn } from "../utils/cn";
  import type { ToolbarFeature, PromptHandler } from "../types";

  let {
    editor,
    features,
    onPromptLink,
  }: {
    editor: Editor;
    features: Set<ToolbarFeature>;
    onPromptLink?: PromptHandler;
  } = $props();

  const has = (f: ToolbarFeature) => features.has(f);

  let showHeadings = $state(false);
  let showColors = $state(false);
  let menuEl: HTMLDivElement | undefined = $state();
  const iconSize = 14;

  const TEXT_COLORS = [
    { label: "기본", value: "" },
    { label: "검정", value: "#000000" },
    { label: "회색", value: "#6b7280" },
    { label: "빨강", value: "#dc2626" },
    { label: "주황", value: "#ea580c" },
    { label: "노랑", value: "#ca8a04" },
    { label: "초록", value: "#16a34a" },
    { label: "파랑", value: "#2563eb" },
    { label: "보라", value: "#7c3aed" }
  ];

  function getCurrentBlockLabel(): string {
    if (editor.isActive("heading", { level: 1 })) return "제목 1";
    if (editor.isActive("heading", { level: 2 })) return "제목 2";
    if (editor.isActive("heading", { level: 3 })) return "제목 3";
    return "본문";
  }

  async function addLink() {
    const previousUrl = editor.getAttributes("link").href || "";
    const url = onPromptLink
      ? await onPromptLink(previousUrl)
      : window.prompt("링크 URL을 입력하세요", previousUrl);
    if (url === null) return;
    if (url === "") {
      editor.chain().focus().extendMarkRange("link").unsetLink().run();
    } else {
      editor
        .chain()
        .focus()
        .extendMarkRange("link")
        .setLink({ href: url })
        .run();
    }
  }

  onMount(() => {
    if (!menuEl) return;

    const plugin = BubbleMenuPlugin({
      pluginKey: bubbleToolbarKey,
      editor,
      element: menuEl,
      shouldShow: ({ editor: e, state }) => {
        const { from, to } = state.selection;
        if (from === to) return false;
        if (e.isActive("codeBlock")) return false;
        if (e.isActive("image")) return false;
        return true;
      },
      tippyOptions: {
        placement: "top",
      },
    });

    editor.registerPlugin(plugin);

    return () => {
      editor.unregisterPlugin(bubbleToolbarKey);
    };
  });
</script>

<div bind:this={menuEl} class="bubble-toolbar-container" style="visibility: hidden">
  <div class="flex items-center gap-0.5 px-1.5 py-1 bg-foreground rounded-full shadow-xl">
    {#if has('h1') || has('h2') || has('h3')}
      <!-- Block type selector -->
      <div class="relative">
        <button
          type="button"
          onclick={() => (showHeadings = !showHeadings)}
          class="flex items-center gap-1 px-2.5 py-1.5 rounded-full text-xs font-medium text-white/80 hover:text-white hover:bg-white/10 transition-colors"
        >
          <Type size={12} />
          {getCurrentBlockLabel()}
        </button>
        {#if showHeadings}
          <div
            class="absolute bottom-full left-0 mb-1 bg-foreground rounded-lg shadow-xl border border-white/10 py-1"
            style="min-width: 120px"
          >
            <button
              type="button"
              class={cn(
                "w-full flex items-center gap-2 px-3 py-1.5 text-xs transition-colors",
                !editor.isActive("heading")
                  ? "text-white bg-white/10"
                  : "text-white/70 hover:text-white hover:bg-white/10",
              )}
              onclick={() => {
                editor.chain().focus().setParagraph().run();
                showHeadings = false;
              }}
            >
              <Type size={12} /> 본문
            </button>
            {#each [1, 2, 3] as level}
              {#if has(level === 1 ? 'h1' : level === 2 ? 'h2' : 'h3')}
              {@const Icon = level === 1 ? Heading1 : level === 2 ? Heading2 : Heading3}
              <button
                type="button"
                class={cn(
                  "w-full flex items-center gap-2 px-3 py-1.5 text-xs transition-colors",
                  editor.isActive("heading", { level })
                    ? "text-white bg-white/10"
                    : "text-white/70 hover:text-white hover:bg-white/10",
                )}
                onclick={() => {
                  editor
                    .chain()
                    .focus()
                    .toggleHeading({ level: level as 1 | 2 | 3 })
                    .run();
                  showHeadings = false;
                }}
              >
                <Icon size={12} /> 제목 {level}
              </button>
              {/if}
            {/each}
          </div>
        {/if}
      </div>

      <div class="w-px h-5 bg-white/20 mx-0.5"></div>
    {/if}

    <!-- Format buttons -->
    {#if has('bold')}
    <button
      type="button"
      onclick={() => editor.chain().focus().toggleBold().run()}
      title="굵게"
      aria-label="굵게"
      class={cn(
        "p-1.5 rounded-full transition-colors",
        editor.isActive("bold")
          ? "bg-white/20 text-white"
          : "text-white/70 hover:text-white hover:bg-white/10",
      )}
    >
      <Bold size={iconSize} />
    </button>
    {/if}
    {#if has('italic')}
    <button
      type="button"
      onclick={() => editor.chain().focus().toggleItalic().run()}
      title="기울임"
      aria-label="기울임"
      class={cn(
        "p-1.5 rounded-full transition-colors",
        editor.isActive("italic")
          ? "bg-white/20 text-white"
          : "text-white/70 hover:text-white hover:bg-white/10",
      )}
    >
      <Italic size={iconSize} />
    </button>
    {/if}
    {#if has('underline')}
      <button
        type="button"
        onclick={() => editor.chain().focus().toggleUnderline().run()}
        title="밑줄"
        aria-label="밑줄"
        class={cn(
          "p-1.5 rounded-full transition-colors",
          editor.isActive("underline")
            ? "bg-white/20 text-white"
            : "text-white/70 hover:text-white hover:bg-white/10",
        )}
      >
        <UnderlineIcon size={iconSize} />
      </button>
    {/if}
    {#if has('strike')}
    <button
      type="button"
      onclick={() => editor.chain().focus().toggleStrike().run()}
      title="취소선"
      aria-label="취소선"
      class={cn(
        "p-1.5 rounded-full transition-colors",
        editor.isActive("strike")
          ? "bg-white/20 text-white"
          : "text-white/70 hover:text-white hover:bg-white/10",
      )}
    >
      <Strikethrough size={iconSize} />
    </button>
    {/if}
    {#if has('text-color')}
      <div class="relative">
        <button
          type="button"
          onclick={() => (showColors = !showColors)}
          title="글자색"
          aria-label="글자색"
          class={cn(
            "p-1.5 rounded-full transition-colors",
            editor.getAttributes("textStyle").color
              ? "bg-white/20 text-white"
              : "text-white/70 hover:text-white hover:bg-white/10",
          )}
        >
          <Palette size={iconSize} />
        </button>
        {#if showColors}
          <div
            class="absolute bottom-full left-0 mb-1 bg-foreground rounded-lg shadow-xl border border-white/10 p-2"
            style="min-width: 160px"
          >
            <div class="grid grid-cols-3 gap-1.5">
              {#each TEXT_COLORS as c}
                <button
                  type="button"
                  title={c.label}
                  class="h-7 rounded-md border border-white/20 transition-transform hover:scale-105 flex items-center justify-center text-xs font-bold bg-white"
                  style="color: {c.value || '#000'}"
                  onclick={() => {
                    if (c.value) {
                      editor.chain().focus().setColor(c.value).run();
                    } else {
                      editor.chain().focus().unsetColor().run();
                    }
                    showColors = false;
                  }}
                >
                  {c.value ? "A" : "×"}
                </button>
              {/each}
            </div>
            <label
              class="mt-2 flex items-center justify-between gap-2 px-1 text-xs text-white/70 cursor-pointer hover:text-white"
            >
              <span>직접 선택</span>
              <input
                type="color"
                class="h-6 w-10 cursor-pointer rounded border border-white/20 bg-transparent p-0"
                value={(editor.getAttributes("textStyle").color as string) || "#000000"}
                onclick={(e) => e.stopPropagation()}
                oninput={(e) => {
                  const v = (e.target as HTMLInputElement).value;
                  editor.chain().focus().setColor(v).run();
                }}
              />
            </label>
          </div>
        {/if}
      </div>
    {/if}
    {#if has('highlight')}
      <button
        type="button"
        onclick={() => editor.chain().focus().toggleHighlight().run()}
        title="하이라이트"
        aria-label="하이라이트"
        class={cn(
          "p-1.5 rounded-full transition-colors",
          editor.isActive("highlight")
            ? "bg-white/20 text-white"
            : "text-white/70 hover:text-white hover:bg-white/10",
        )}
      >
        <Highlighter size={iconSize} />
      </button>
    {/if}
    {#if has('code')}
    <button
      type="button"
      onclick={() => editor.chain().focus().toggleCode().run()}
      title="코드"
      aria-label="코드"
      class={cn(
        "p-1.5 rounded-full transition-colors",
        editor.isActive("code")
          ? "bg-white/20 text-white"
          : "text-white/70 hover:text-white hover:bg-white/10",
      )}
    >
      <Code size={iconSize} />
    </button>
    {/if}

    {#if has('link')}
    <div class="w-px h-5 bg-white/20 mx-0.5"></div>

    <button
      type="button"
      onclick={addLink}
      title="링크"
      aria-label="링크"
      class={cn(
        "p-1.5 rounded-full transition-colors",
        editor.isActive("link")
          ? "bg-white/20 text-white"
          : "text-white/70 hover:text-white hover:bg-white/10",
      )}
    >
      <LinkIcon size={iconSize} />
    </button>
    {/if}

    {#if has('align-left') || has('align-center') || has('align-right')}
      <div class="w-px h-5 bg-white/20 mx-0.5"></div>

      <!-- Alignment -->
      {#if has('align-left')}
      <button
        type="button"
        onclick={() => editor.chain().focus().setTextAlign("left").run()}
        title="왼쪽 정렬"
        aria-label="왼쪽 정렬"
        class={cn(
          "p-1.5 rounded-full transition-colors",
          editor.isActive({ textAlign: "left" })
            ? "bg-white/20 text-white"
            : "text-white/70 hover:text-white hover:bg-white/10",
        )}
      >
        <AlignLeft size={iconSize} />
      </button>
      {/if}
      {#if has('align-center')}
      <button
        type="button"
        onclick={() => editor.chain().focus().setTextAlign("center").run()}
        title="가운데 정렬"
        aria-label="가운데 정렬"
        class={cn(
          "p-1.5 rounded-full transition-colors",
          editor.isActive({ textAlign: "center" })
            ? "bg-white/20 text-white"
            : "text-white/70 hover:text-white hover:bg-white/10",
        )}
      >
        <AlignCenter size={iconSize} />
      </button>
      {/if}
      {#if has('align-right')}
      <button
        type="button"
        onclick={() => editor.chain().focus().setTextAlign("right").run()}
        title="오른쪽 정렬"
        aria-label="오른쪽 정렬"
        class={cn(
          "p-1.5 rounded-full transition-colors",
          editor.isActive({ textAlign: "right" })
            ? "bg-white/20 text-white"
            : "text-white/70 hover:text-white hover:bg-white/10",
        )}
      >
        <AlignRight size={iconSize} />
      </button>
      {/if}
    {/if}
  </div>
</div>
